default_stages: [ pre-commit ]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.10
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.8.13
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: pytest
        stages: [ pre-push ]
        name: pytest
        entry: uv run pytest
        pass_filenames: false
        language: system
        types: [ python ]
