= MeteoFungi
:toc: auto
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]


[NOTE]
====
Name change incoming: I discovered the project https://www.meteofunghi.it/[meteofunghi], an Italian web site that seems to predict mushrooms occurences with meteo data. I had not previously known of the project; however, since its purpose is very similar to ours and their name is nearly identical, I decided to change the name of our project. Their work deserves respect and they were the first ones to come up with the name meteofunghi, so it is only fair that we adapt.
Therefore, the MeteoFungi repository will change its name to MeteoShrooms. Not immediately, though, because I currently lack insight what consequences a name change has. I don't want to mess up the project, so you'll have to wait a bit for the new name...
This means that the dashboard is now available at https://meteoshrooms.streamlit.app[https://meteoshrooms.streamlit.app]
====

[NOTE]
====
Contributors Welcome!
See section _Contributing_ for more info...
====

With _MeteoFungi_, You can keep track of the perfect conditions for mushroom hunting.
We take Open Government Data (OGD) from the official Swiss Meteorological Service MeteoSwiss to calculate key metrics.

== Motivation

While hunting mushrooms happens in nature, a lot of the planning can be carried out beforehand.
Where are possible areas to find boletes?
Should You leave the house right now or are you already too late?
And will Your current small basket be large enough or is it time to invest in something bigger?
Meteorological data, time series of past findings as well as other datasets can give us valuable insights.

== Concept

=== Spatial

Currently, the _MeteoFungi_ project is focussed on Switzerland, as https://www.meteoswiss.admin.ch[MeteoSwiss] has started to provide access to their data as https://www.meteoswiss.admin.ch/services-and-publications/service/open-data.html[OGD].

=== Technical

A main aim is to have sound results calculated efficiently.
Therefore, Python _Polars_ is used for calculations, wherever possible.
Its _LazyFrames_ optimize the workflow.
Data quality is validated through _Pandera_.
Compressed _Parquet_-Files save storage space and up-/download bandwith.

=== Visualization

Metrics and time series visulizations are currently hosted as a Streamlit dashboard, so please check it out at https://meteofungi.streamlit.app[https://meteofungi.streamlit.app]

== Contributing

_MeteoFungi_ is right at the beginning of the development process: I've got some ideas and inspirations as well as motivation to write Python code; but so far, _MeteoFungi_ cannot realistically increase Your chances of success when hunting mushrooms.
However, that is about to change: If you want to contribute to the project, feel free to fork it, improve it and create a Pull Request.
Alternatively, create an Issue. _MeteoFungi_ is mainly written in Python at the moment.
Should you fancy coding in Rust, be my guest.

Furthermore, my aim is to create a model that learns from past mushroom sightings, local soil and meteo conditions, etc., and which then helps predict when a user has the chance to find edible mushrooms of their choosing.
If you feel well versed in creating such a model, now's your time.


