= Contributing to MeteoShrooms
:toc: auto
:icons: font

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

:docs: https://docs.spring.io/spring-boot
:github: https://github.com/spring-projects/spring-boot

The MeteoShrooms project welcomes contributions of all kinds!
You can submit them in the form of Pull Requests (PR).
For clear bug-fixes / typos etc. just submit a PR.
For new features, feature request or if there is any doubt in how to fix a bug, it is recommended to open an issue prior to starting work.

== Prerequisites

MeteoShrooms uses https://docs.astral.sh/uv/[uv] for packaging and dependency management.
To start developing MeteoShrooms, install uv using the https://docs.astral.sh/uv/getting-started/installation/[recommended method].

Next, you'll need to https://docs.github.com/en/get-started/quickstart/fork-a-repo[create a _fork_] (your own personal copy) of the MeteoShrooms repository and _clone_ it to your local machine.
Now you're almost ready to start coding on your local copy of the MeteoShrooms source code.

Next, enter the directory that contains your local clone of MeteoShrooms and open a terminal.
The present guide uses Bash syntax; depending on your setup (operating system, etc.), you might have to change some commands.
If you're on Linux, you'll most probably be fine.

Install the Python packages required to run and develop MeteoShrooms with:

[source,bash]
----
uv sync --all-groups
----

uv will take care of downloading and installing the appropriate package versions.
Furthermore, it creates a new virtual environment.
If you don't like uv or otherwise want to use a different package manager, feel free to do so.
Note, however, that all guides on this repo solely support uv.

You are now ready to run the MeteoShrooms dashboard from within the newly created virtual environment:

[source,bash]
----
uv run streamlit run dashboard.py
----

This should open up your web browser and show the MeteoShrooms dashboard.

All of the following instructions assume that you are within the created virtual environment.
Commands should hence be run with `uv run [commandXY]`

Feel free to have a look at the files in the MeteoShrooms folder.
You will notice that most of them are copies of the files on the MeteoShrooms online repository.
There will be additional files and folders used by uv, git, etc.
Understanding them is not required to contribute to MeteoShrooms.
You are left to investigate on your own, should you feel interested.

== Developing

At this point, you are ready to start coding.
It is worth noting a few basics first, however:

* Before you spend considerable time developing a new feature, make sure it has a chance of being implemented in MeteoShrooms.
Otherwise you might feel unpleasantly surprised when your Pull Request is rejected.
Feel free to get prior feedback on your ideas.
* Always document your code.
MeteoShrooms uses docstrings in the https://numpydoc.readthedocs.io/en/latest/format.html[numpy format].
Where it helps to understand your code, add line comments.

Before each https://github.com/git-guides/git-commit[commit], you should:

1. Run tests and ensure they pass,
2. Ensure type-checking passes,
3. Lint the code,
4. Format the code.
5. Lock dependencies

You do not need to start each of these steps individually, if you want to commit your changes.
When you used uv to install all the dependencies, the tool `pre-commit` was added to your system.
The MeteoShrooms repository contains https://github.com/networkscientist/meteofungi/blob/master/.pre-commit-config.yaml[configuration files] outlining each step.
From within your local MeteoShrooms folder, run:

[source,bash]
----
pre-commit install
----

Now, each time you commit your files, `pre-commit` runs all of the steps.

During the coding process, it often makes sense to run one or multiple of the pre-commit steps and look at the results.
This can give you valuable information.

Therefore, in the following paragraphs, we'll present how to run each step individually.
Feel free to skip them, if you're fine with running all of them with `pre-commit`.

If you want to run the pre-commit scripts on all of your files manually, you can run:

[source,bash]
----
pre-commit run --all-files
----

=== Testing

MeteoShrooms uses tests to help prevent the introduction of bugs into working code.
Thus, we use `pytest`:

[source,bash]
----
uv run pytest
----

Tests are located in the `tests` folder and each test file has the following naming convention: `test_[module_name].py`, for example `test_data_preparation.py`.
If you know how to write tests, add your tests for any function you add to the code, otherwise at least ensure that all currently defined tests pass.
If you upload code that has failing tests, you will be asked to resolve the issues before a PR can be accepted.

=== Type-Checking

To check for code quality issues regarding types, use:

[sourc,bash]
----
uv run mypy
----

This checks performs a static type analysis.
Take a look at the errors (if there are any) and resolve them, as good as you are able to.
Currently, I lack knowledge to fix all mypy errors, so feel free to either add your insights to the repo or ignore any error you do not understand, for the time being.

=== Linting

To check for code quality issues, we use the ruff linter:

[source,bash]
----

uv run ruff check --fix

----

This tool inspects the source code to see whether is conforms to a pre-defined set of rules (see the section `[tool.ruff.lint]` in https://github.com/networkscientist/meteofungi/blob/master/pyproject.toml[pyproject.toml] for the rules and the https://docs.astral.sh/ruff/rules/[ruff documentation] for a detailed explanation of each rule).
If an issue can easily be fixed automatically, ruff will try to do so, otherwise you will have to do it manually.
In either case, ruff will provide you with details for each issue in the terminal.
Code that has errors must not be commited.
It will most likely be rejected, when you try a Pull Request.
Always make sure to fix all errors prior to commiting your code.

=== Formatting

Although there are recommendations about Python code style (see for example https://peps.python.org/pep-0008/[PEP8 - Style Guide for Python Code]), there is still plenty of room to disagree about style details.
MeteoShrooms uses ruff to automatically format code according to a set of predefined rules (see the section `[tool.ruff.format]` in https://github.com/networkscientist/meteofungi/blob/master/pyproject.toml[pyproject.toml] for the rules and the https://docs.astral.sh/ruff/formatter/[ruff documentation] for a detailed explanation).
Always make sure your code is properly formatted prior to commiting it with:

[source,bash]
----

uv run ruff format

----

=== Locking Dependencies

Most of the contributions will not alter package versions of the project dependencies.
If they do, however, it is necessary to _lock_ them in a text file.
This allows users to work with a working set of packages, whose versions have been tested to work with MeteoShrooms.
Since we use uv for managing our project, you can run:

[source,bash]
----
uv lock
----

This will write the package versions to a lockfile.
Do not modify the lockfile manually.
Also, don't change dependencies or bump versions without prior consultation, or your Pull Request will be rejected.

After successfully completing all of the above steps, either manually or with `pre-commit`, you are ready to commit your changes.

=== Documenting your changes

Currently, we do not have documentation beyond the Asciidoc-Files on the repository (e.g. no readthedocs, etc.).
This means that code and functionality are entirely documented either in the source code files or the Asciidoc files.
Any contributions should be properly described in commits, PRs and, most importantly, in the source code itself.
If you do not consider yourself good enough to document your code, please ask, there will always be someone willing to help out.
Contributions lacking useful documentation will not be accepted in PRs.

=== Update CHANGELOG and CONTRIBUTORS

Before submitting your Pull Request, update the `CHANGELOG.adoc` file, briefly describing what you've done.
Be sure to follow the format seen in the rest of the document.

If this is your first time contributing to MeteoShrooms, also add your Github username and optionally your real name to CONTRIBUTORS.adoc.

== Creating a Pull Request

Once you are happy with your changes and have ensured that all of the steps outlined above have been followed (and checks/tests passed), you can create a Pull Request (PR).
Github offers a guide on how to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork[do this].
Make sure you include a good description of your changes (e.g. what it achieves, how it integrates into existing code, etc.), and link the PR to any https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue[relevant issues].

When you create your PR, the checks outlined above will be run again.
If they fail, please attempt to fix them as we're unlikely to be able to review your code changes until then.
Feel free to ask for help in the community, if you don't know how to fix an error.
Someone may be able to assist you in the process.

=== Code Review

After the checks in your PR pass, someone will review your contribution.
This includes a line-by-line check of the changes you submitted.
There may be some discussion and, in most cases, a few iterations will be required to find a solution that works best.
This is standard procedure in developing software, so do not be discouraged when you are asked to make changes to your code.

== Next Steps

Once the PR is approved, your changes will be merged into the `main` branch of the MeteoShrooms repository.
Anyone cloning the repo will now get the source code with your contribution implemented.
This is the time for celebration: Well done, the MeteoShrooms community is grateful to you!

== Credits

This contribution guide has been inspired by https://github.com/Textualize/rich/blob/ea9d4db5d84b4e834979304e3053bf757daae322/CONTRIBUTING.md[Rich].
At the time of the initial creation of this document, their license was https://github.com/Textualize/rich/blob/ea9d4db5d84b4e834979304e3053bf757daae322/LICENSE[MIT]